#!/usr/bin/env bash
# Paper Table 12 / FLOCK entity-prediction walk + ensemble budgets.
# Sourced by eval/queue_eval_kg.sh and finetune/finetune_kg.sh / queue_finetune_kg.sh.
#
# Sets: KG_WALK_NUM  KG_ENSEMBLE_P  KG_BATCH_SIZE  KG_BPE
#   Eval / post-FT test use n and P. Finetune always does a full training epoch
#   (KG_BPE is unused). KG_BATCH_SIZE is the FT link batch size.
# Datasets not in the table use n=128, P=16, bs=8, bpe=full.

# shellcheck disable=SC2034

kg_lookup_protocol() {
  local ds="$1"
  KG_WALK_NUM=128
  KG_ENSEMBLE_P=16
  KG_BATCH_SIZE=8
  KG_BPE=full

  case "${ds}" in
    FB15K_237|WN18RR|WN18RR_FEAT|CODEX_MEDIUM|NELL995|CONCEPTNET100K|CONCEPTNET100K_FEAT|HM_INDIGO)
      KG_WALK_NUM=128; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    CODEX_SMALL)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=32; KG_BPE=full ;;
    CODEX_LARGE)
      KG_WALK_NUM=512; KG_ENSEMBLE_P=2; KG_BATCH_SIZE=4; KG_BPE=2000 ;;
    YAGO310)
      KG_WALK_NUM=512; KG_ENSEMBLE_P=8; KG_BATCH_SIZE=4; KG_BPE=2000 ;;
    WD_SINGER)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    NELL23K)
      KG_WALK_NUM=32; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    FB15K237_10)
      KG_WALK_NUM=32; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    FB15K237_20|FB15K237_50)
      KG_WALK_NUM=64; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    HETIONET)
      KG_WALK_NUM=512; KG_ENSEMBLE_P=2; KG_BATCH_SIZE=8; KG_BPE=4000 ;;
    DBPEDIA100K)
      KG_WALK_NUM=512; KG_ENSEMBLE_P=2; KG_BATCH_SIZE=4; KG_BPE=1000 ;;
    ARISTOV4)
      KG_WALK_NUM=256; KG_ENSEMBLE_P=4; KG_BATCH_SIZE=8; KG_BPE=full ;;
    FB15K237_IND|FB15K237_IND:v1|FB15K237_IND:v2|FB15K237_IND:v3|FB15K237_IND:v4)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WN18RR_IND|WN18RR_IND:v1|WN18RR_IND:v2|WN18RR_IND:v3|WN18RR_IND:v4|WN18RR_IND_FEAT|WN18RR_IND_FEAT:v1|WN18RR_IND_FEAT:v2|WN18RR_IND_FEAT:v3|WN18RR_IND_FEAT:v4)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    NELL_IND|NELL_IND:v1|NELL_IND:v2|NELL_IND:v3|NELL_IND:v4)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    ILPC2022_SMALL)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    ILPC2022_LARGE)
      KG_WALK_NUM=64; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    FB_INGRAM:25|FB_INGRAM:50)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    FB_INGRAM:75|FB_INGRAM:100)
      KG_WALK_NUM=8; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WK_INGRAM:25|WK_INGRAM:75)
      KG_WALK_NUM=4; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WK_INGRAM:50|WK_INGRAM:100)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    NL_INGRAM:0|NL_INGRAM:25|NL_INGRAM:75)
      KG_WALK_NUM=2; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    NL_INGRAM:50|NL_INGRAM:100)
      KG_WALK_NUM=4; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WIKITOPICS_MT1_TAX)
      KG_WALK_NUM=4; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WIKITOPICS_MT1_HEALTH|WIKITOPICS_MT2_SCI|WIKITOPICS_MT4_SCI|WIKITOPICS_MT4_HEALTH)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    WIKITOPICS_MT2_ORG|WIKITOPICS_MT3_ART|WIKITOPICS_MT3_INFRA)
      KG_WALK_NUM=32; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=16; KG_BPE=full ;;
    FB_NELL)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=16; KG_BPE=full ;;
    METAFAM)
      KG_WALK_NUM=1; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    HM_1K)
      KG_WALK_NUM=16; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
    HM_3K)
      KG_WALK_NUM=32; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=16; KG_BPE=full ;;
    HM_5K)
      KG_WALK_NUM=64; KG_ENSEMBLE_P=16; KG_BATCH_SIZE=8; KG_BPE=full ;;
  esac
}
