#!/usr/bin/env bash
# Paper (ICLR 2027) dataset lists. Sourced by paper-table queues.
# Do not sbatch this file.
#
# shellcheck disable=SC2034

# Tables 4 / 19: attributed NC graphs (Pokec = 100k BFS, top-10 classes).
PAPER_NC_DATASETS=(
  CORNELL TEXAS WISCONSIN
  BRAZIL EUROPE USA
  CHAMELEON_FILTERED SQUIRREL_FILTERED
  ACTOR
  CORA CITESEER PUBMED
  PHOTO COMPUTERS
  WIKI_CS FULL_DBLP FULL_CORA
  ROMAN_EMPIRE AMAZON_RATINGS
  CO_CS CO_PHYSICS
  HM_CATEGORIES
  POKEC_REGIONS_100K_TOP10
  CITY_PARIS CITY_SHANGHAI CITY_LA
)

# Table 7: GRIDS + nofeat real NC (same splits as Table 4).
PAPER_NC_LONGRANGE_DATASETS=(
  GRIDS PUBMED FULL_DBLP CO_CS CO_PHYSICS
)

# Table 3: 10 homogeneous AnyGraph LP graphs.
PAPER_LP_DATASETS=(
  ANYGRAPH_CITESEER
  ANYGRAPH_CORA
  ANYGRAPH_PUBMED
  ANYGRAPH_CS
  ANYGRAPH_DDI
  ANYGRAPH_PRODUCTS_HOME
  ANYGRAPH_P2P_GNUTELLA06
  ANYGRAPH_EMAIL_ENRON
  ANYGRAPH_PROTEINS_SPEC1
  ANYGRAPH_SOC_EPINIONS1
)

# Table 16: UniLP vs Wander, sampled Recall@20, two 70/10/20 splits.
PAPER_UNILP_DATASETS=(
  UNILP_CELEGANS
  UNILP_USAIR
  UNILP_NS
  UNILP_PB
  UNILP_CORA
  UNILP_CS
  UNILP_SNAP_MUSAE_FACEBOOK
)

# Table 16 featured Wander rows (Cora / CS / Facebook).
PAPER_UNILP_FEATURED_DATASETS=(
  UNILP_CORA
  UNILP_CS
  UNILP_SNAP_MUSAE_FACEBOOK
)

# Table 6 MiniLM 2×2: features on/off × relations on/off. Feat keys use
# precomputed PCA-32 MiniLM; structure twins are the same graphs without
# features. Same Flock n/P via kg_protocol.sh (Table 13).
PAPER_KG_FEAT_DATASETS=(
  CONCEPTNET100K_FEAT
  WN18RR_FEAT
  WN18RR_IND_FEAT:v1
  WN18RR_IND_FEAT:v2
  WN18RR_IND_FEAT:v3
  WN18RR_IND_FEAT:v4
)
PAPER_KG_COMPOSITION_STRUCT_DATASETS=(
  CONCEPTNET100K
  WN18RR
  WN18RR_IND:v1
  WN18RR_IND:v2
  WN18RR_IND:v3
  WN18RR_IND:v4
)

# Table 12: FLOCK-protocol KG entity prediction (same list as kg_protocol.sh).
PAPER_KG_DATASETS=(
  FB15K_237 WN18RR CODEX_MEDIUM
  CODEX_SMALL CODEX_LARGE
  YAGO310 DBPEDIA100K CONCEPTNET100K HETIONET ARISTOV4 NELL995
  WD_SINGER NELL23K FB15K237_10 FB15K237_20 FB15K237_50
  FB15K237_IND:v1 FB15K237_IND:v2 FB15K237_IND:v3 FB15K237_IND:v4
  WN18RR_IND:v1 WN18RR_IND:v2 WN18RR_IND:v3 WN18RR_IND:v4
  NELL_IND:v1 NELL_IND:v2 NELL_IND:v3 NELL_IND:v4
  FB_INGRAM:25 FB_INGRAM:50 FB_INGRAM:75 FB_INGRAM:100
  WK_INGRAM:25 WK_INGRAM:50 WK_INGRAM:75 WK_INGRAM:100
  NL_INGRAM:0 NL_INGRAM:25 NL_INGRAM:50 NL_INGRAM:75 NL_INGRAM:100
  HM_1K HM_3K HM_5K HM_INDIGO
  ILPC2022_SMALL ILPC2022_LARGE
  WIKITOPICS_MT1_TAX WIKITOPICS_MT1_HEALTH
  WIKITOPICS_MT2_ORG WIKITOPICS_MT2_SCI
  WIKITOPICS_MT3_ART WIKITOPICS_MT3_INFRA
  WIKITOPICS_MT4_SCI WIKITOPICS_MT4_HEALTH
  METAFAM FB_NELL
)
